### ISSUE TITLE
FDTD-related files in dedicated folder

### ISSUE THREAD

**Issue by MisterHW** [LubomirJagos/FreeCAD-OpenEMS-Export#10]
Currently, the use of FreeCAD-OpenEMS-Export (and subsequent simulation) produces a set of files in the same folder as the .FCStd file. 

- having multiple simulation-specific files in the project folder without the ability to move them to a different folder isn't ideal
- alternative sets of simulation settings cannot easily be managed
- there is currently no folder name or text field through which the intent of the simulation and its particularities could be logged. A folder name could be a convenient way to express the nature of a particular simulation

Proposed solution:
- settings file(s) continue to reside in the .FCStd project directory
- for each settings file, there would be a folder with the same name
- the associated folder receives all output generated 

Associated folders may contain a large amount of output data and should be added to `.gitignore` when the whole project is kept in a repository.

## Related Topic: Handling Multiple Studies/Simulations

As of this writing, the user is presented with multiple buttons to load and save settings files:

![image](https://user-images.githubusercontent.com/24977335/198847549-1cb5b4a5-56cf-48b4-8509-108507cb0f76.png)

To refine the load/save interactions, the role of a default file may need to be re-assessed.
For example, modern IDEs start with a project selector / browser view, with the option to automatically load the most recent project upon startup. 

During use (from personal experience), the Export dialog is frequently opened and closed, and thus unnecessary overhead (i.e. a prompt that asks the user to select a particular settings file to continue) needs to be avoided.
At the same time, the load / save handling shouldn't have such a prominent place in the UI while at the same time lacking intuitiveness. When upon first start the user needs to press "New Simulation", the causality is established.

Currently, "New Simulation" is unintentional, as it is merely the dialog state before loading a settings file. Once a settings file is loaded, the dialog must be closed and re-started to flush it. Separating the selection of a simulation settings file and the rest of the dialog functionality would also clarify "Load" (during editing) as "re-load, discarding unsaved changes", and could probably be removed from the editing state altogether, as this workflow can be provided through "close without saving changes" followed by loading.

Finally, selecting one of the available simulation settings files would be obviated. 

Thus, future improvements in handling multiple simulation settings files both clean up the project folder, and will come in handy when improving settings selection and load/save logic.

**Comment by LubomirJagos** [comment]
This issue was fixed now, only two buttons were left "Open Settings" and "Save Settings" which are asking which .ini file to open, afterwards when simulation is opened or save whe simulation files are generated, they are generated into separate folder with same name as settings .ini file name.
On macro start if simulation is created without load or save at .m file generating user is asked to saved simulation if no, files are generated same way as now in current FreeCAD file folder.

So now issue with separate folders for simulations is solved, but keep in mind there is absolute path in openEMS .xml in tmp/ so if you copy your simulation folder anywhere on drive, you need to re-run .m file, everything in tmp/ is temporary :D
